version: '3.7'
services:
  applada-nginx:
    image: nginx
    container_name: applada-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - applada-api
  applada-db:
    image: kartoza/postgis
    container_name: applada-db
    environment:
      POSTGRES_DB: applada
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/applada-db:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  applada-api:
    container_name: applada-api
    environment:
      API_HOST: applada.com.br
      DB_HOST: applada-db
    build: 
      context: '.'
    command: sh -c '/bin/wait-for applada-db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:80'
    volumes:
      - .:/applada-api/
    expose:
      - 80
    depends_on:
    - applada-db
