version: 2.1
jobs:
  test:
    docker: 
      - image: igorxp5/applada-api:latest
        name: applada-api
        auth:
          username: igorxp5
          password: $DOCKERHUB_PASSWORD
      - image: kartoza/postgis
        name: applada-db
        environment:
          POSTGRES_DB: applada
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: /bin/wait-for applada-db:5432
      - run: python manage.py test -d --noinput api_v1/tests/*
workflows:
  version: 2
  workflow:
    jobs:
      - test