# Generated by Django 3.0.2 on 2020-01-13 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('limit_participants', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('soccer', 'Soccer'), ('volleyball', 'Voleyball'), ('basketball', 'Basketball')], default=None, max_length=15)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('password_digest', models.CharField(default=None, max_length=65)),
                ('registred_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Match')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.User')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.User'),
        ),
        migrations.CreateModel(
            name='MatchSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Match')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.User')),
            ],
            options={
                'unique_together': {('match', 'username')},
            },
        ),
    ]
