# Generated by Django 3.0.2 on 2020-01-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20200119_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchsubscription',
            old_name='created_date',
            new_name='date',
        ),
    ]
