# Generated by Django 3.0.2 on 2020-01-14 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20200114_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registred_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
